import document from '../lib/window/document';
import createRenderer from '../renderer/dom/todo-static.jsx';
import createController from '../controller/todo-static.js';
import state from '../lib/state';
import BASESTATE from '../lib/BASESTATE';
const controller = createController(state(BASESTATE));
const view = createRenderer(document.getElementsByTagName('div')[0]);
controller.subscribers.push(view.send);
view.subscribers.push(controller.send);
controller.send();
